sbatch ./scripts/base/claude_claude.sh
sbatch ./scripts/base/claude_deepseek.sh
sbatch ./scripts/base/claude_gemini.sh
sbatch ./scripts/base/claude_gpt.sh
sbatch ./scripts/base/claude_llama.sh
sbatch ./scripts/base/claude_mistral.sh
sbatch ./scripts/base/claude_qwen.sh
sbatch ./scripts/base/deepseek_claude.sh
sbatch ./scripts/base/deepseek_deepseek.sh
sbatch ./scripts/base/deepseek_gemini.sh
sbatch ./scripts/base/deepseek_gpt.sh
sbatch ./scripts/base/deepseek_llama.sh
sbatch ./scripts/base/deepseek_mistral.sh
sbatch ./scripts/base/deepseek_qwen.sh
sbatch ./scripts/base/gemini_claude.sh
sbatch ./scripts/base/gemini_deepseek.sh
sbatch ./scripts/base/gemini_gemini.sh
sbatch ./scripts/base/gemini_gpt.sh
sbatch ./scripts/base/gemini_llama.sh
sbatch ./scripts/base/gemini_mistral.sh
sbatch ./scripts/base/gemini_qwen.sh
sbatch ./scripts/base/gpt_claude.sh
sbatch ./scripts/base/gpt_deepseek.sh
sbatch ./scripts/base/gpt_gemini.sh
sbatch ./scripts/base/gpt_gpt.sh
sbatch ./scripts/base/gpt_llama.sh
sbatch ./scripts/base/gpt_mistral.sh
sbatch ./scripts/base/gpt_qwen.sh
sbatch ./scripts/base/llama_claude.sh
sbatch ./scripts/base/llama_deepseek.sh
sbatch ./scripts/base/llama_gemini.sh
sbatch ./scripts/base/llama_gpt.sh
sbatch ./scripts/base/llama_llama.sh
sbatch ./scripts/base/llama_mistral.sh
sbatch ./scripts/base/llama_qwen.sh
sbatch ./scripts/base/mistral_claude.sh
sbatch ./scripts/base/mistral_deepseek.sh
sbatch ./scripts/base/mistral_gemini.sh
sbatch ./scripts/base/mistral_gpt.sh
sbatch ./scripts/base/mistral_llama.sh
sbatch ./scripts/base/mistral_mistral.sh
sbatch ./scripts/base/mistral_qwen.sh
sbatch ./scripts/base/qwen_claude.sh
sbatch ./scripts/base/qwen_deepseek.sh
sbatch ./scripts/base/qwen_gemini.sh
sbatch ./scripts/base/qwen_gpt.sh
sbatch ./scripts/base/qwen_llama.sh
sbatch ./scripts/base/qwen_mistral.sh
sbatch ./scripts/base/qwen_qwen.sh